version: "3"
services:
  web:
    image: pgonyan/friendlyhello
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet

  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - misdatos:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet

volumes:
    misdatos:

networks:
  webnet:

